import Head from 'next/head'
import styles from './AppLayout.module.css'

const AppLayout = ({ children, pageTitle, backButton }) =>
{
    

    return (
        <div className={styles.container}>
            <Head>
                <title>Claim App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {typeof backButton === 'function' && (<button className={styles.back} onClick={backButton}>Kembali</button>)}
                <h1 className={styles.title}>{pageTitle}</h1>
                {children}
            </main>
        </div>
    )
}

export default AppLayout